services:

  mysql:
    image: mysql:8.4

    container_name: origin-mysql

    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: origin_ecommerce

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

  api:

    build: .

    container_name: origin-api

    depends_on:
      - mysql

    ports:
      - "9090:9090"

    env_file:
      - .env

volumes:
  mysql_data: